name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout rgbds
        uses: actions/checkout@master
        with:
          path: rgbds
          ref: v0.8.0
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo make install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Make
        run: |
          make -j$(nproc)
  validate:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Mono
        run: |
          sudo apt install ca-certificates gnupg
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt install mono-mcs
          sudo apt update
      - name: Validate
        run: mono tools/PokeGen2TextValidator.exe maps/Route29.asm